better debian packaging of services

diff --git a/dev/lifecycle/debian b/dev/lifecycle/debian
--- a/dev/lifecycle/debian
+++ b/dev/lifecycle/debian
@@ -110,8 +110,8 @@ CONTROL=${DEB_SOURCES}/DEBIAN/control
 DIST=unstable
 FIRST=1
 
-if [ ! -f "${BIN_SOURCES}/cnb-rates-unit-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-unit-linux-${TARGET_ARCHITECTURE}")
+if [ ! -f "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}")
   exit 1
 fi
 
@@ -122,26 +122,26 @@ fi
 
 mkdir -p ${DEB_SOURCES}/openbank/services/cnb-rates
 
-if [ -f "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-unit" ] ; then
-  rm -f ${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-unit
+if [ -f "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-import" ] ; then
+  rm -f ${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-import
 fi
 
 if [ -f "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-rest" ] ; then
   rm -f ${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-rest
 fi
 
-du -hs "${BIN_SOURCES}/cnb-rates-unit-linux-${TARGET_ARCHITECTURE}"
+du -hs "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}"
 du -hs "${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}"
 
 cp \
-  "${BIN_SOURCES}/cnb-rates-unit-linux-${TARGET_ARCHITECTURE}" \
-  "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-unit"
+  "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}" \
+  "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-import"
 
 cp \
   "${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}" \
   "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-rest"
 
-file "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-unit"
+file "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-import"
 file "${DEB_SOURCES}/openbank/services/cnb-rates/cnb-rates-rest"
 
 generate_changelog
