Jenkinsfile

diff --git a/dev/lifecycle/debian b/dev/lifecycle/debian
--- a/dev/lifecycle/debian
+++ b/dev/lifecycle/debian
@@ -4,6 +4,7 @@ set -eu
 trap exit INT TERM
 
 VERSION=""
+SOURCE=""
 TARGET_ARCHITECTURE=""
 
 while [ $# -gt 0 ] ; do
@@ -11,13 +12,19 @@ key="$1"
 
 case $key in
 
+  --source)
+    SOURCE="$2"
+    shift
+    shift
+  ;;
+
   --arch)
     TARGET_ARCHITECTURE="$2"
     shift
     shift
   ;;
 
-  -v|--version)
+  --version)
     VERSION="$2"
     shift
     shift
@@ -30,14 +37,53 @@ case $key in
 esac
 done
 
-if [ ! "${VERSION}" ] ; then
+if [ -z "${VERSION}" ] ; then
   (>&2 echo "version not provided")
   exit 1
 fi
 
-if [ ! "${TARGET_ARCHITECTURE}" ] ; then
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "source not provided")
+  exit 1
+fi
+
+if [ -z "${TARGET_ARCHITECTURE}" ] ; then
   (>&2 echo "target architecture not provided (use e.g. --arch amd64)")
   exit 1
+fi
+
+DEB_SOURCES="${SOURCE}/debian_${TARGET_ARCHITECTURE}"
+BIN_SOURCES="${SOURCE}/bin"
+
+if [ ! -d "${DEB_SOURCES}" ] ; then
+  (>&2 echo "packaging for ${TARGET_ARCHITECTURE} is not supported")
+  exit 1
+fi
+
+if [ ! -f "${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}")
+  exit 1
+fi
+
+if [ ! -f "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}")
+  exit 1
+fi
+
+if [ ! -f "${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}")
+  exit 1
+fi
+
+mkdir -p ${DEB_SOURCES}/usr/bin
+if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-rest" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-rest
+fi
+if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-import" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-import
+fi
+if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-batch" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-batch
 fi
 
 generate_manpage() {
@@ -192,41 +238,6 @@ check_files() {
 }
 
 ################################################################################
-
-PKGS="$(pwd)/packaging"
-DEB_SOURCES="${PKGS}/debian_${TARGET_ARCHITECTURE}"
-BIN_SOURCES="${PKGS}/bin"
-
-if [ ! -d "${DEB_SOURCES}" ] ; then
-  (>&2 echo "packaging for ${TARGET_ARCHITECTURE} is not supported")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-mkdir -p ${DEB_SOURCES}/usr/bin
-if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-rest" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-rest
-fi
-if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-import" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-import
-fi
-if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-batch" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-batch
-fi
 
 case ${TARGET_ARCHITECTURE} in
 
