more industry standard packaging, bashism improvements

diff --git a/dev/lifecycle/debian b/dev/lifecycle/debian
--- a/dev/lifecycle/debian
+++ b/dev/lifecycle/debian
@@ -3,39 +3,24 @@
 set -eu
 trap exit INT TERM
 
+################################################################################
+
 VERSION=""
 SOURCE=""
 TARGET_ARCHITECTURE=""
-
+TARGET_PACKAGE=""
 while [ $# -gt 0 ] ; do
 key="$1"
-
 case $key in
-
-  --source)
-    SOURCE="$2"
-    shift
-    shift
-  ;;
-
-  --arch)
-    TARGET_ARCHITECTURE="$2"
-    shift
-    shift
-  ;;
-
-  --version)
-    VERSION="$2"
-    shift
-    shift
-  ;;
-
-  *)
-    shift
-  ;;
-
+  --source)   SOURCE="$2";              shift; shift; ;;
+  --arch)     TARGET_ARCHITECTURE="$2"; shift; shift; ;;
+  --pkg)      TARGET_PACKAGE="$2";      shift; shift; ;;
+  --version)  VERSION="$2";             shift; shift; ;;
+  *)                                    shift;        ;;
 esac
 done
+
+################################################################################
 
 if [ -z "${VERSION}" ] ; then
   (>&2 echo "version not provided")
@@ -47,145 +32,31 @@ if [ -z "${SOURCE}" ] ; then
   exit 1
 fi
 
+if [ -z "${TARGET_PACKAGE}" ] ; then
+  (>&2 echo "[error] target package not provided")
+  exit 1
+fi
+
 if [ -z "${TARGET_ARCHITECTURE}" ] ; then
   (>&2 echo "target architecture not provided (use e.g. --arch amd64)")
   exit 1
 fi
 
-DEB_SOURCES="${SOURCE}/debian_${TARGET_ARCHITECTURE}"
-BIN_SOURCES="${SOURCE}/bin"
+################################################################################
 
-if [ ! -d "${DEB_SOURCES}" ] ; then
-  (>&2 echo "packaging for ${TARGET_ARCHITECTURE} is not supported")
-  exit 1
-fi
+lifecycle::debian::generate_changelog() {
+  echo "[info] (${TARGET_PACKAGE}_${TARGET_ARCHITECTURE}) generating changelog"
 
-if [ ! -f "${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-mkdir -p ${DEB_SOURCES}/usr/bin
-if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-rest" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-rest
-fi
-if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-import" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-import
-fi
-if [ -f "${DEB_SOURCES}/usr/bin/cnb-rates-batch" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/cnb-rates-batch
-fi
-
-generate_manpage() {
-  mkdir -p ${DEB_SOURCES}/usr/share/man/man8
-
-  target_batch="${DEB_SOURCES}/usr/share/man/man8/cnb-rates-batch.8"
-  target_import="${DEB_SOURCES}/usr/share/man/man8/cnb-rates-import.8"
-  target_rest="${DEB_SOURCES}/usr/share/man/man8/cnb-rates-rest.8"
-
-  if [ -f ${target_batch} ] ; then
-    rm -f ${target_batch}
-  fi
-
-  if [ -f ${target_batch}.gz ] ; then
-    rm -f ${target_batch}.gz
-  fi
-
-  if [ -f ${target_import} ] ; then
-    rm -f ${target_import}
-  fi
-
-  if [ -f ${target_import}.gz ] ; then
-    rm -f ${target_import}.gz
-  fi
-
-  if [ -f ${target_rest} ] ; then
-    rm -f ${target_rest}
-  fi
-
-  if [ -f ${target_rest}.gz ] ; then
-    rm -f ${target_rest}.gz
-  fi
-
-cat > ${target_batch} <<EOL
-.TH CNB-RATES-BATCH 8 2019 "CNB Rates Batch" "OpenBank CNB Rates Batch Processing"
-.SH NAME
-cnb-rates-batch \- starts openbank cnb exchange rates batch processing
-.SH DESCRIPTION
-The cnb rates batch processes newly downloaded cnb rates
-.EE
-EOL
-
-cat > ${target_import} <<EOL
-.TH CNB-RATES-IMPORT 8 2019 "CNB Rates Import" "OpenBank CNB Rates Cloud Import"
-.SH NAME
-cnb-rates-import \- starts openbank cnb exchange rates cloud import
-.SH DESCRIPTION
-The
-.B pldd
-cnb rates import creates offline mirror of official cnb rates cloud
-.EE
-EOL
-
-cat > ${target_rest} <<EOL
-.TH CNB-RATES-REST 8 2019 "CNB Rates REST" "OpenBank CNB Rates REST Server"
-.SH NAME
-cnb-rates-rest \- starts openbank cnb exchange rates REST server
-.SH DESCRIPTION
-The cnb rates rest provides REST server for accessing cnb rates
-.EE
-EOL
-
-  cat ${target_batch} | gzip -n -9 > ${target_batch}.gz
-  rm ${target_batch}
-
-  cat ${target_import} | gzip -n -9 > ${target_import}.gz
-  rm ${target_import}
-
-  cat ${target_rest} | gzip -n -9 > ${target_rest}.gz
-  rm ${target_rest}
-}
-
-generate_changelog() {
-  mkdir -p ${DEB_SOURCES}/usr/share/doc/cnb-rates
-
-  target="${DEB_SOURCES}/usr/share/doc/cnb-rates/changelog"
+  target="${SOURCE}/debian/changelog"
 
   if [ -f ${target} ] ; then
     rm -f ${target}
   fi
 
-  if [ -f ${target}.Debian.gz ] ; then
-    rm -f ${target}.Debian.gz
-  fi
-
   touch ${target}
 
-  VER="${VERSION}"
-  tag=HEAD
-  ADDS=$(echo ${VER} | sed -e 's/~.*//' | cut -s -d- -f2 | sed '/^[[:space:]]*$/d')
-
-  if [[ -z "${ADDS// }" ]] ; then
-    DATE=$(date '+%a, %-d %b %Y %H:%M:%S %z')
-    echo "cnb-rates (${VER}) unstable; urgency=low" >> ${target}
-    echo "" >> ${target}
-    echo "  * includes non-released commits" >> ${target}
-    echo "" >> ${target}
-    echo " -- Jan Cajthaml <jan.cajthaml@gmail.com>  ${DATE}" >> ${target}
-    echo "" >> ${target}
-  fi
-
   PAIRS=()
+  tag=HEAD
   prev_tag=HEAD
   for tag in $(git tag --sort=-v:refname | awk '{arr[i++]=$0} END {while (i>0) print arr[--i] }') ; do
     PAIRS+=("${prev_tag} ${tag}")
@@ -196,74 +67,53 @@ generate_changelog() {
   for ((i=${#idx[@]} - 1; i >= 0; i--)) ; do
     tag_from=${PAIRS[idx[i]]%% *}
     tag_to=${PAIRS[idx[i]]#* }
-
     DATE=$(git log -1 --format=%cD ${tag_to})
-
     commits=$(echo "$(git log --no-merges --pretty=oneline --pretty=format:%s ^${tag_from} ${tag_to})" | sed '/^[[:space:]]*$/d' | uniq)
-
     if [[ -n "${commits// }" ]] ; then
-
-      echo "cnb-rates (${tag_to#v}) stable; urgency=low" >> ${target}
+      echo "${TARGET_PACKAGE} (${tag_to#v}) stable; urgency=medium" >> ${target}
       echo "" >> ${target}
-
       echo "${commits}" | \
       while read note ; do
-        echo "  * $(tr '[:lower:]' '[:upper:]' <<< ${note:0:1})${note:1}" >> ${target}
+        line="$(tr '[:lower:]' '[:upper:]' <<< ${note:0:1})${note:1}"
+        echo "  * ${line:0:75}" >> ${target}
       done
-
       echo "" >> ${target}
-
       echo " -- Jan Cajthaml <jan.cajthaml@gmail.com>  ${DATE}" >> ${target}
       echo "" >> ${target}
     fi
   done
 
-  case "${VERSION}" in
-    *+*)
-      cat ${target} | gzip -n -9 > ${target}.Debian.gz
-      ;;
-    *)
-      cat ${target} | gzip -n -9 > ${target}.gz
-      ;;
-  esac
+  echo "[info] (${TARGET_PACKAGE}_${TARGET_ARCHITECTURE}) checking misspell"
 
-  rm ${target}
+  /go/bin/misspell -q -locale US -source=text -w ${target}
 }
 
-check_files() {
-  chmod 0755 "${DEB_SOURCES}/DEBIAN/control"
-  chmod 0755 "${DEB_SOURCES}/DEBIAN/postinst"
-  chmod 0755 "${DEB_SOURCES}/DEBIAN/postrm"
-  chmod 0755 "${DEB_SOURCES}/DEBIAN/preinst"
-  chmod 0755 "${DEB_SOURCES}/usr/bin/cnb-rates-rest"
-  chmod 0755 "${DEB_SOURCES}/usr/bin/cnb-rates-import"
-  chmod 0755 "${DEB_SOURCES}/usr/bin/cnb-rates-batch"
+lifecycle::debian::package() {
+  echo "[info] (${TARGET_PACKAGE}_${TARGET_ARCHITECTURE}) running dpkg-buildpackage"
+  local CC=gcc
+  case ${TARGET_ARCHITECTURE} in
+    armhf) CC=arm-linux-gnueabihf-gcc ;;
+    arm64) CC=aarch64-linux-gnu-gcc   ;;
+    *)     CC=gcc                     ;;
+  esac
+
+  cd ${SOURCE} && \
+  \
+  CC=${CC} \
+    dpkg-buildpackage \
+    --host-arch=${TARGET_ARCHITECTURE} \
+    -tc -uc -b -rfakeroot
+
+  find ".." -name "${TARGET_PACKAGE}_*_${TARGET_ARCHITECTURE}.*" -exec mv {} bin/ \;
+}
+
+lifecycle::lintian() {
+  echo "[info] (${TARGET_PACKAGE}_${TARGET_ARCHITECTURE}) running lintian"
+  find bin -name "${TARGET_PACKAGE}_*_${TARGET_ARCHITECTURE}.deb" -exec fakeroot lintian --pedantic {} \;
 }
 
 ################################################################################
 
-cp \
-  "${BIN_SOURCES}/cnb-rates-rest-linux-${TARGET_ARCHITECTURE}" \
-  "${DEB_SOURCES}/usr/bin/cnb-rates-rest"
-cp \
-  "${BIN_SOURCES}/cnb-rates-import-linux-${TARGET_ARCHITECTURE}" \
-  "${DEB_SOURCES}/usr/bin/cnb-rates-import"
-cp \
-  "${BIN_SOURCES}/cnb-rates-batch-linux-${TARGET_ARCHITECTURE}" \
-  "${DEB_SOURCES}/usr/bin/cnb-rates-batch"
-
-generate_changelog
-generate_manpage
-
-sed -i 's/Version.*/Version: '${VERSION#v}'/' "${DEB_SOURCES}/DEBIAN/control"
-
-find "${BIN_SOURCES}" -name "cnb-rates_*_${TARGET_ARCHITECTURE}.deb" -exec rm -f {} \;
-
-check_files
-
-dpkg-deb --build "${DEB_SOURCES}" "${BIN_SOURCES}"
-
-find "${BIN_SOURCES}" -name "cnb-rates_*_${TARGET_ARCHITECTURE}.deb" -exec fakeroot lintian --pedantic {} \;
-find "${BIN_SOURCES}" -name "cnb-rates_*_${TARGET_ARCHITECTURE}.deb" -exec du -hs {} \;
-
-exit 0
+lifecycle::debian::generate_changelog
+lifecycle::debian::package
+lifecycle::lintian
