cleanup

diff --git a/dev/lifecycle/package b/dev/lifecycle/package
--- a/dev/lifecycle/package
+++ b/dev/lifecycle/package
@@ -16,14 +16,32 @@ package_service() {
 
   echo "[info] packaging for ${platform}/${arch}"
 
-  GOOS=${platform} \
-  GOARCH=${arch} \
-  CGO_ENABLED=0 \
-  \
-  go build -a -o ${output} || {
-    (>&2 echo "unable to build for ${platform}/${arch}")
-    exit 1
-  }
+  case ${arch} in
+
+    arm)
+      GOOS=${platform} \
+      GOARM=7 \
+      GOARCH=arm \
+      CGO_ENABLED=0 \
+      \
+      go build -a -o ${output} || {
+        (>&2 echo "unable to build for ${platform}/arm")
+        exit 1
+      }
+    ;;
+
+    *)
+      GOOS=${platform} \
+      GOARCH=${arch} \
+      CGO_ENABLED=0 \
+      \
+      go build -a -o ${output} || {
+        (>&2 echo "unable to build for ${platform}/${arch}")
+        exit 1
+      }
+    ;;
+
+  esac
 
   chmod +x ${output}
 }
