stability and uniformity with other OB projects

diff --git a/dev/lifecycle/package b/dev/lifecycle/package
--- a/dev/lifecycle/package
+++ b/dev/lifecycle/package
@@ -3,47 +3,62 @@
 set -eu
 trap exit INT TERM
 
-dist="packaging/bin"
-targets=("linux/amd64")
+TARGET_ARCHITECTURE="linux/amd64"
+TARGET_PACKAGE=""
 
 package_service() {
-  local arch=${2#*/}
-  local platform=${2%%/*}
-  local output=${1}/${platform}-${arch}
+  local working_dir=/go/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
+  local arch=${TARGET_ARCHITECTURE#*/}
+  local platform=${TARGET_ARCHITECTURE%%/*}
+  local output=$(pwd)/packaging/bin/${TARGET_PACKAGE}-${platform}-${arch}
+
   if [ -f ${output} ] ; then
     rm -f ${output}
   fi
 
-  echo "[info] packaging for ${platform}/${arch}"
+  cd ${working_dir}
+
+  echo "[info] cleaning"
+  go clean
+
+  echo "[info] packaging ${TARGET_PACKAGE} for ${platform}/${arch}"
 
   case ${arch} in
 
-    arm)
+    armhf)
       GOOS=${platform} \
       GOARM=7 \
+      CC=arm-linux-gnueabihf-gcc \
       GOARCH=arm \
-      CGO_ENABLED=0 \
+      CGO_ENABLED=1 \
       \
       go build -a -o ${output} || {
-        (>&2 echo "unable to build for ${platform}/arm")
+        (>&2 echo "[error] unable to build for ${platform}/armhf")
+        exit 1
+      }
+    ;;
+
+    amd64)
+      GOOS=${platform} \
+      CC=gcc \
+      GOARCH=amd64 \
+      CGO_ENABLED=1 \
+      \
+      go build -a -o ${output} || {
+        (>&2 echo "[error] unable to build for ${platform}/amd64")
         exit 1
       }
     ;;
 
     *)
-      GOOS=${platform} \
-      GOARCH=${arch} \
-      CGO_ENABLED=0 \
-      \
-      go build -a -o ${output} || {
-        (>&2 echo "unable to build for ${platform}/${arch}")
-        exit 1
-      }
+      (>&2 echo "[error] unsupported target ${platform}/${arch}")
+      exit 1
     ;;
 
   esac
 
   chmod +x ${output}
+  file ${output}
 }
 
 while [ $# -gt 0 ] ; do
@@ -51,36 +66,30 @@ key="$1"
 
 case $key in
 
-    --target)
-      targets=($(sed "s/,/ /g" <<< "$2"))
-      shift
-      shift
-    ;;
+  --arch)
+    TARGET_ARCHITECTURE="$2"
+    shift
+    shift
+  ;;
 
-    -o|--output)
-      dist="$2"
-      shift
-      shift
-    ;;
+  --pkg)
+    TARGET_PACKAGE="$2"
+    shift
+    shift
+  ;;
 
-    *)
-      shift
-    ;;
+  *)
+    shift
+  ;;
 
 esac
 done
 
-
-echo "[info] cleaning"
-go clean
-
-for target in ${targets[@]} ; do
-  package_service ${dist} ${target}
-done
-
-if [ ! -f ${dist}/linux-amd64 ] ; then
-  (>&2 echo "[error] ${dist}/linux-amd64 not found")
+if [ ! "${TARGET_PACKAGE}" ] ; then
+  (>&2 echo "[error] target package not provided")
   exit 1
 fi
+
+package_service
 
 echo "[info] done"
diff --git a/dev/lifecycle/release b/dev/lifecycle/release
--- a/dev/lifecycle/release
+++ b/dev/lifecycle/release
@@ -31,34 +31,43 @@ esac
 done
 
 if [ ! "${VERSION}" ] ; then
-  (>&2 echo "version not provided")
+  (>&2 echo "[error] version not provided")
   exit 1
 fi
 
 if [ ! "${ACCESS_TOKEN}" ] ; then
-  (>&2 echo "github access token not provided")
+  (>&2 echo "[error] github access token not provided")
   exit 1
 fi
 
-REPO=jancajthaml-openbank/lake
+REPO=$(git ls-remote --get-url)
+REPO=${REPO%.git}
+REPO=${REPO#*:}
+REPO=${REPO#/}
+REPO=${REPO#/}
+REPO=${REPO#/}
+REPO=${REPO#github.com}
+REPO=${REPO#/}
+REPO=${REPO}
 
-echo "start release of ${REPO}:${VERSION} "
+echo "[info] start release of ${REPO}:${VERSION}"
 
 RELEASE_INFO="https://api.github.com/repos/${REPO}/releases/tags/${VERSION}"
-response=$(curl \
+response=$(
+  curl \
     --silent \
     -H "Authorization: token ${ACCESS_TOKEN}" \
     ${RELEASE_INFO} \
 )
 
-RELEASE_ID=$(echo "$response" | jq -r .id)
+RELEASE_ID=$(echo "${response}" | jq -r .id)
 RELEASE_URI="https://api.github.com/repos/${REPO}/releases"
 
 if [ "${RELEASE_ID}" != "null" ] ; then
-  (>&2 echo "release ${VERSION} already exists")
+  (>&2 echo "[error] release ${VERSION} already exists")
   exit 1
 else
-  echo "creating new release ${VERSION}"
+  echo "[info] creating new release ${VERSION}"
 fi
 
 PAYLOAD=$(cat <<-END
@@ -75,37 +84,28 @@ END
 
 response=$(
   curl \
-    --fail \
-    --request POST \
+    -X POST \
     -H "Authorization: token ${ACCESS_TOKEN}" \
+    --fail \
     --silent \
     --data "$(echo ${PAYLOAD})" \
     ${RELEASE_URI}
 )
 
-UPLOAD_URL=$(echo $response | jq -r .upload_url | sed -e "s/{?name,label}//")
+UPLOAD_URL=$(echo ${response} | jq -r .upload_url | sed -e "s/{?name,label}//")
 
-assets_dir=packaging/bin
-
-for asset in $(ls -1 packaging/bin); do
-  abspath="${assets_dir}/${asset}"
-
-  if [ ! -f $abspath ] ; then
-    (>&2 echo "asset ${abspath} not found")
-    exit 1
-  fi
-
-  echo "uploading ${asset}"
+for asset in $(ls -d -1 $(pwd)/packaging/bin/*.*) ; do
+  echo "[info] uploading ${asset}"
 
   curl \
     --fail \
-    --request POST \
+    -X POST \
     -# \
     --output /dev/null \
-    --data-binary "@${abspath}" \
-    -H "Authorization: token ${ACCESS_TOKEN}" \
+    --data-binary "@${asset}" \
+    -H "Authorization: token $ACCESS_TOKEN" \
     -H "Content-Type: application/binary" \
-    "${UPLOAD_URL}?name=${asset}"
+    "${UPLOAD_URL}?name=$(basename ${asset})"
 done
 
-echo "released ${VERSION}"
+echo "[info] released ${VERSION}"
